name: Sonar-Scanner action
author: LowCostCustoms
description: -|
  Runs sonar-scanner, submits analysis results and retrieves the quality
  gate status if needed.
inputs:
  image:
    description: -|
      The name of an image containing sonar-scanner cli.
    required: false
    default: "sonarsource/sonar-scanner-cli:latest"
  wait-for-quality-gate:
    description: -|
      Specifies whether the SonarQube task status should be retrieved after the
      analysis is finished. By default it's "true" which means that the action
      will fail if task finishes with non-success status or doesn't finish in
      time. However you can set this value to "false" to disable such a
      behavior.
    required: false
    default: "true"
  quality-gate-wait-timeout:
    description: -|
      Specifies the maximum amount of time - a non-negative number followed by
      one of the suffixes "m", "s" or "h", which is considered maximum amount
      of time during after which an unfinished SonarQube task is considered
      failed.
    required: false
    default: "2m"
  sonar-host-url:
    description: -|
      The url by which the SonarQube server is accessible.
    required: false
    default: ""
  sonar-host-cert:
    description: -|
      The PEM-encoded sonar host certificate if any.
    required: false
    default: ""
  project-file-location:
    description: -|
      Sonar-Scanner project file location, relative to the sources-location
      variable. By default this value is empty.
    required: false
    default: ""
  sources-mount-point:
    description: -|
      The place where directory with the project sources will be mounted in a
      sonar-scanner docker container. By default the project sources you
      specified in the sources-location input are mounted into the /app/ dir.
    required: false
    default: "/app"
  sources-location:
    description: -|
      The place where the project sources are located. By default this input
      points to the current github workspace root.
    required: false
    default: ${{ github.workspace }}
  log-level:
    description: -|
      Determines the verbosity of the actoion output. Should be one of debug,
      info, warning or error.
    required: false
    default: info
  tls-skip-verify:
    description: -|
      If true skips sonar host TLS certificate verification.
    required: false
    default: false
  sonar-login:
    description: -|
      An authentication token or SonarQube user login.
    required: false
    default: ""
  sonar-password:
    description: -|
      The password for the account associated with the `sonar-login`.
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Run sonar-scanner
      shell: bash
      env:
        IMAGE: ${{ inputs.image }}
        WAIT_FOR_QUALITY_GATE: ${{ inputs.wait-for-quality-gate }}
        QUALITY_GATE_WAIT_TIMEOUT: ${{ inputs.quality-gate-wait-timeout }}
        SONAR_HOST_URL: ${{ inputs.sonar-host-url }}
        SONAR_HOST_CERT: ${{ inputs.sonar-host-cert }}
        PROJECT_FILE_LOCATION: ${{ inputs.project-file-location }}
        SOURCES_MOUNT_POINT: ${{ inputs.sources-mount-point }}
        SOURCES_LOCATION: ${{ inputs.sources-location }}
        LOG_LEVEL: ${{ inputs.log-level }}
        TLS_SKIP_VERIFY: ${{ inputs.tls-skip-verify }}
        SONAR_LOGIN: ${{ inputs.sonar-login }}
        SONAR_PASSWORD: ${{ inputs.sonar-password }}
      working-directory: ${{ github.action_path }}
      run: ${{ github.action_path }}/action-entrypoint.sh
